CIRCUITPY_WIFI_SSID = "Flia Garcia"
CIRCUITPY_WIFI_PASSWORD = "VELYZ_JuanisY"

MQTT_BROKER = "9b0fee708e1e4d8eae9f88b7e5325840.s1.eu.hivemq.cloud"
MQTT_PORT = 8883
MQTT_USERNAME = "LisaGarc"
MQTT_PASSWORD = "030814.Li"
MQTT_SSL = "true"